export const courses = [
  "Machine Learning",
  "Artificial Intelligence",
  "Full Stack",
  "Data Science",
];

export const genders = ["Male", "Female"];

export const students = [
  {
    name: "John Doe",
    age: 25,
    gender: "Male",
    course: "Machine Learning",
  },
  {
    name: "Jane Smith",
    age: 30,
    gender: "Female",
    course: "Artificial Intelligence",
  },
  {
    name: "Alex Johnson",
    age: 22,
    gender: "Male",
    course: "Full Stack",
  },
  {
    name: "Emily Davis",
    age: 28,
    gender: "Female",
    course: "Data Science",
  },
  {
    name: "Jane Smith",
    age: 30,
    gender: "Female",
    course: "Machine Learning",
  },
  {
    name: "Emily Davis",
    age: 28,
    gender: "Female",
    course: "Artificial Intelligence",
  },
  {
    name: "Olivia Wilson",
    age: 24,
    gender: "Female",
    course: "Full Stack",
  },
  {
    name: "Sophia Anderson",
    age: 27,
    gender: "Female",
    course: "Data Science",
  },
  {
    name: "Isabella Martinez",
    age: 29,
    gender: "Female",
    course: "Machine Learning",
  },
  {
    name: "Ava Lewis",
    age: 26,
    gender: "Female",
    course: "Artificial Intelligence",
  },
  {
    name: "Mia Ward",
    age: 31,
    gender: "Female",
    course: "Full Stack",
  },
  {
    name: "Charlotte Hughes",
    age: 28,
    gender: "Female",
    course: "Data Science",
  },
  {
    name: "Scarlett Ramirez",
    age: 23,
    gender: "Female",
    course: "Machine Learning",
  },
  {
    name: "Lily Price",
    age: 30,
    gender: "Female",
    course: "Artificial Intelligence",
  },
];

export const instructors = [
  {
    id: "1",
    name: "John",
    age: 25,
    gender: "Male",
    years: 2,
    course: "Machine Learning",
    status: "active",
  },
  {
    id: "2",
    name: "Sarah",
    age: 28,
    gender: "Female",
    years: 3,
    course: "Artificial Intelligence",
    status: "active",
  },
  {
    id: "3",
    name: "Michael",
    age: 23,
    gender: "Male",
    years: 1,
    course: "Full Stack",
    status: "active",
  },
  {
    id: "4",
    name: "Emily",
    age: 26,
    gender: "Female",
    years: 2,
    course: "Data Science",
    status: "active",
  },
  {
    id: "5",
    name: "David",
    age: 30,
    gender: "Male",
    years: 4,
    course: "Machine Learning",
    status: "active",
  },
  {
    id: "6",
    name: "Jessica",
    age: 27,
    gender: "Female",
    years: 3,
    course: "Artificial Intelligence",
    status: "active",
  },
  {
    id: "7",
    name: "Alex",
    age: 24,
    gender: "Male",
    years: 1,
    course: "Full Stack",
    status: "active",
  },
  {
    id: "8",
    name: "Sophia",
    age: 29,
    gender: "Female",
    years: 2,
    course: "Data Science",
    status: "active",
  },
  {
    id: "9",
    name: "Daniel",
    age: 26,
    gender: "Male",
    years: 3,
    course: "Machine Learning",
    status: "active",
  },
  {
    id: "10",
    name: "Olivia",
    age: 24,
    gender: "Female",
    years: 1,
    course: "Artificial Intelligence",
    status: "active",
  },
  {
    id: "11",
    name: "James",
    age: 27,
    gender: "Male",
    years: 2,
    course: "Full Stack",
    status: "inactive",
  },
  {
    id: "12",
    name: "Emma",
    age: 25,
    gender: "Female",
    years: 3,
    course: "Data Science",
    status: "inactive",
  },
  {
    id: "13",
    name: "William",
    age: 28,
    gender: "Male",
    years: 4,
    course: "Machine Learning",
    status: "inactive",
  },
  {
    id: "14",
    name: "Ava",
    age: 23,
    gender: "Female",
    years: 1,
    course: "Artificial Intelligence",
    status: "inactive",
  },
  {
    id: "15",
    name: "Benjamin",
    age: 30,
    gender: "Male",
    years: 2,
    course: "Full Stack",
    status: "inactive",
  },
  {
    id: "16",
    name: "Mia",
    age: 27,
    gender: "Female",
    years: 3,
    course: "Data Science",
    status: "inactive",
  },
  {
    id: "17",
    name: "Alexander",
    age: 24,
    gender: "Male",
    years: 2,
    course: "Machine Learning",
    status: "inactive",
  },
  {
    id: "18",
    name: "Charlotte",
    age: 29,
    gender: "Female",
    years: 1,
    course: "Artificial Intelligence",
    status: "inactive",
  },
  {
    id: "19",
    name: "Henry",
    age: 26,
    gender: "Male",
    years: 2,
    course: "Full Stack",
    status: "inactive",
  },
  {
    id: "20",
    name: "Amelia",
    age: 25,
    gender: "Female",
    years: 3,
    course: "Data Science",
    status: "inactive",
  },
];
